site_name: KiloGuide

nav:
  - 'Home': 'index.md'
  - 'Guides':
    - 'Guides summary': './guides/guide-index.md'
    - 'Getting started': './guides/getting-started.md'
    - 'Coding for kilobots': './guides/coding-for-kilobots.md'
    - 'Compile your code': './guides/compile-your-code.md'
    - 'Transfer and run your program': './guides/transfer-and-run-your-program.md'
    - 'Use the debug feature': './guides/use-the-debug-feature.md'
  - 'Tutorials':
    - 'Tutorials summary': './tutorials/tuto-index.md'
    - 'Race Around the World': './tutorials/tuto1.md'
    - 'Full Metal Kilobot': './tutorials/tuto2.md'
    - "King-o-bot's Games": './tutorials/tuto3.md'
    - 'Morphogenetics': './tutorials/tuto4.md'
    - 'Rush Hour': './tutorials/tuto5.md'
  - 'About': 'about.md'

theme:
  name: 'readthedocs'

markdown_extensions:
  - 'admonition'

use_directory_urls: false
